#!/bin/sh

echo "SAVE_VARIABLE VARIABLE=fix_scv VALUE=1
SAVE_VARIABLE VARIABLE=fix_e0011 VALUE=1
SAVE_VARIABLE VARIABLE=fix_e0017 VALUE=1
SAVE_VARIABLE VARIABLE=force_md5 VALUE=1
SAVE_VARIABLE VARIABLE=close_dialogs VALUE=2
SAVE_VARIABLE VARIABLE=wifi VALUE=1
">/tmp/printer

echo "Recommend installed"
